@extends('layouts.dashboard')

@section('dashboard-content')
<!-- ============================================================
     MEMBER REPORTS PAGE
     ============================================================ -->
<div class="animate-[fadeIn_0.4s_ease] space-y-4">
  <div class="flex items-center justify-between">
    <h2 class="text-lg font-bold" :class="darkMode?'text-white':'text-primary-900'">Member Reports</h2>
    <div class="flex gap-2">
      <button class="px-4 py-2 rounded-xl bg-primary-600 text-white text-xs font-semibold hover:bg-primary-500 transition-all">
        <i class="fa-solid fa-download mr-1.5"></i> Export All
      </button>
    </div>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
    <div class="card rounded-2xl p-5 border" :class="darkMode?'border-[#1a3328]':'border-primary-100'">
      <h3 class="text-xs font-bold uppercase tracking-wider mb-3" :class="darkMode?'text-primary-400':'text-primary-500'">Member Listing</h3>
      <p class="text-xs mb-4" :class="darkMode?'text-primary-300':'text-gray-600'">Complete list of all registered members with status and join dates.</p>
      <button class="w-full py-2 rounded-lg bg-primary-900/10 text-primary-500 text-xs font-bold hover:bg-primary-900/20 transition-all">Generate Report</button>
    </div>
    <div class="card rounded-2xl p-5 border" :class="darkMode?'border-[#1a3328]':'border-primary-100'">
      <h3 class="text-xs font-bold uppercase tracking-wider mb-3" :class="darkMode?'text-primary-400':'text-primary-500'">Dormant Members</h3>
      <p class="text-xs mb-4" :class="darkMode?'text-primary-300':'text-gray-600'">Members who haven't performed any transactions in the last 90 days.</p>
      <button class="w-full py-2 rounded-lg bg-primary-900/10 text-primary-500 text-xs font-bold hover:bg-primary-900/20 transition-all">Generate Report</button>
    </div>
    <div class="card rounded-2xl p-5 border" :class="darkMode?'border-[#1a3328]':'border-primary-100'">
      <h3 class="text-xs font-bold uppercase tracking-wider mb-3" :class="darkMode?'text-primary-400':'text-primary-500'">New Registrations</h3>
      <p class="text-xs mb-4" :class="darkMode?'text-primary-300':'text-gray-600'">Report of members who joined within the current fiscal period.</p>
      <button class="w-full py-2 rounded-lg bg-primary-900/10 text-primary-500 text-xs font-bold hover:bg-primary-900/20 transition-all">Generate Report</button>
    </div>
  </div>

  <!-- Recent Downloads -->
  <div class="card rounded-2xl p-5">
    <h3 class="text-sm font-bold mb-4" :class="darkMode?'text-white':'text-primary-900'">Recent Downloads</h3>
    <div class="space-y-3">
      <div class="flex items-center justify-between p-3 rounded-xl transition-colors" :class="darkMode?'bg-primary-900/20 hover:bg-primary-900/30':'bg-primary-50 hover:bg-primary-100'">
        <div class="flex items-center gap-3">
          <div class="w-8 h-8 rounded-lg bg-red-100 text-red-600 flex items-center justify-center">
            <i class="fa-solid fa-file-pdf"></i>
          </div>
          <div>
            <p class="text-xs font-bold" :class="darkMode?'text-white':'text-primary-900'">Full_Member_List_May_2024.pdf</p>
            <p class="text-[10px]" :class="darkMode?'text-primary-400':'text-gray-500'">Generated by Admin • 14 May 2024</p>
          </div>
        </div>
        <button class="text-primary-500 hover:text-primary-400"><i class="fa-solid fa-download"></i></button>
      </div>
    </div>
  </div>
</div>
@endsection
